using System;
using System.Collections.Generic;
using Archipelago.MultiClient.Net;
using Archipelago.MultiClient.Net.Enums;
using MelonLoader;
using Newtonsoft.Json.Linq;

namespace SuperhotArchipelago.Core
{
    /// <summary>
    /// Thin wrapper around the official Archipelago.MultiClient.Net session. Owns the
    /// WebSocket connection to the AP server; ArchipelagoConnection itself never touches
    /// game/Unity state -- that's LocationManager/ItemManager's job.
    /// </summary>
    public class ArchipelagoConnection
    {
        private readonly MelonLogger.Instance _log;
        public ArchipelagoSession? Session { get; private set; }
        public bool IsConnected { get; private set; }

        // Real, explicit user request: Core/ArchipelagoConnectApp.cs surfaces connection
        // problems in-game instead of only in the (easy to miss) MelonLoader console.
        // Cleared at the start of every Connect() attempt, set on failure so the UI has
        // something more specific than "Not connected" to show.
        public string? LastError { get; private set; }

        // How many of the other 31 levels must be completed before "34 - Free" opens,
        // even once its own access item is received -- see Core/LevelAccessGuard.cs for
        // where this is actually enforced. Comes from this room's slot data (see below),
        // itself sourced from the player's own YAML (apworld/superhot/Options.py's
        // levels_required_for_free). The 25 here is just a fallback for before a
        // successful connect, or for a room generated by an apworld old enough not to
        // send this key at all -- kept equal to Options.py's own default so the two
        // can't quietly disagree if one is ever changed without the other.
        public int LevelsRequiredForFree { get; private set; } = 25;

        // Real, explicit user request (Notifications feature): popups should only fire
        // for genuinely new items received live during play, not for the full item
        // history the server replays through the same ItemReceived event on every
        // connect/reconnect (confirmed real behavior -- this is exactly why
        // UnlockState.cs already ends up fully rebuilt after every reconnect with no
        // extra bookkeeping). Core/ItemManager.cs uses this timestamp plus a short grace
        // window (see its own comment) to tell that replay burst apart from a genuinely
        // live item, rather than comparing against Session.Items.AllItemsReceived's count
        // directly -- the client library's own docs/decompile don't pin down precisely
        // when that collection is populated relative to TryConnectAndLogin returning vs.
        // ItemReceived firing, and a wrong assumption there would either spam popups for
        // old items on every reconnect or silently swallow real live ones. A short
        // real-time grace period after a successful connect sidesteps needing that
        // internal ordering guarantee at all.
        public DateTime ConnectedAtUtc { get; private set; }

        // Real, explicit user request: "a yaml setting to exclude levels with
        // boring/slow gameplay (dog 1-3 and longway)". apworld/superhot/Options.py's
        // ExcludeSlowLevels toggle removes a level's location(s)/item from the pool
        // entirely for a player who turns it on -- this is how the mod learns WHICH
        // levels that was, via this room's slot data, rather than hardcoding its own
        // copy of apworld/superhot/Items.py's SLOW_LEVEL_NAMES that could drift out of
        // sync with it. Keyed by LevelEntry.Order (matches what
        // apworld/superhot/__init__.py's fill_slot_data() actually sends), not LevelId --
        // Order is the one identifier both sides already share without needing
        // LevelCatalog's own gameId extraction. Empty by default, same fallback
        // reasoning as LevelsRequiredForFree above: a room generated by an apworld
        // version older than this feature simply won't send this key, and "nothing
        // excluded" is exactly the correct behavior for that case.
        public HashSet<int> ExcludedLevelOrders { get; private set; } = new();

        public event Action? Connected;

        public ArchipelagoConnection(MelonLogger.Instance log)
        {
            _log = log;
        }

        public void Connect(string server, string slotName, string? password = null)
        {
            LastError = null;
            IsConnected = false;

            if (string.IsNullOrEmpty(server) || string.IsNullOrEmpty(slotName))
            {
                LastError = "Server and Slot are both required.";
                _log.Warning($"Not connecting: {LastError}");
                return;
            }

            Session = ArchipelagoSessionFactory.CreateSession(server);

            // TODO: itemsHandlingFlags -- AllItems is the simplest starting point (get told
            // about every item including our own), can be narrowed later.
            //
            // The whole call is wrapped in a try/catch (needed once connecting became
            // reachable from in-game text entry, see Core/ArchipelagoConnectApp.cs):
            // TryConnectAndLogin can throw outright on some bad inputs (e.g. a malformed
            // server string) rather than just returning an unsuccessful result -- without
            // this, an in-game typo could throw past this method's caller and take down
            // more than just this one connect attempt.
            try
            {
                var result = Session.TryConnectAndLogin(
                    "SUPERHOT",
                    slotName,
                    ItemsHandlingFlags.AllItems,
                    password: password
                );

                if (!result.Successful)
                {
                    LastError = "Login failed -- check server address, slot name, and password.";
                    _log.Error($"Failed to connect to Archipelago server: {server}");
                    return;
                }

                // TryConnectAndLogin defaults requestSlotData to true (confirmed against
                // the client library's own source), so a successful LoginResult here is
                // always really a LoginSuccessful carrying this room's slot data -- the
                // "is" pattern match below is just the type-safe way to reach it, not a
                // real possibility of it being something else.
                if (result is LoginSuccessful success &&
                    success.SlotData.TryGetValue("levels_required_for_free", out object? rawRequired))
                {
                    // Comes back through Newtonsoft.Json as a boxed numeric type (long in
                    // practice for a plain JSON integer) -- Convert.ToInt32 handles that
                    // (or int/double, if the server ever serializes it differently)
                    // rather than assuming one specific boxed type and risking an
                    // InvalidCastException on a direct (int) cast.
                    LevelsRequiredForFree = Convert.ToInt32(rawRequired);
                    _log.Msg($"Slot data: {LevelsRequiredForFree} other levels required to enter '34 - Free'.");
                }
                else
                {
                    _log.Warning("Slot data had no 'levels_required_for_free' -- falling back to " +
                        $"{LevelsRequiredForFree}. Expected if this room was generated from an " +
                        "apworld version older than this feature.");
                }

                // Real, explicit user request: "exclude levels with boring/slow gameplay
                // (dog 1-3 and longway)" -- see ExcludedLevelOrders' own comment. Comes
                // back through Newtonsoft.Json as a JArray (a boxed JSON array, same
                // general "boxed via Newtonsoft" pattern as levels_required_for_free's
                // own rawRequired above) -- ToObject<List<int>>() converts each element
                // the same way a plain JSON int would convert on its own.
                if (result is LoginSuccessful excludedSuccess &&
                    excludedSuccess.SlotData.TryGetValue("excluded_level_orders", out object? rawExcluded) &&
                    rawExcluded is JArray excludedArray)
                {
                    ExcludedLevelOrders = new HashSet<int>(excludedArray.ToObject<List<int>>() ?? new List<int>());
                    if (ExcludedLevelOrders.Count > 0)
                    {
                        _log.Msg($"Slot data: {ExcludedLevelOrders.Count} level(s) excluded from " +
                            "tracking (ExcludeSlowLevels) -- always unlocked, no checks sent for them.");
                    }
                }
                else
                {
                    ExcludedLevelOrders = new HashSet<int>();
                }
            }
            catch (Exception ex)
            {
                LastError = ex.Message;
                _log.Error($"Failed to connect to Archipelago server '{server}': {ex.Message}");
                return;
            }

            IsConnected = true;
            ConnectedAtUtc = DateTime.UtcNow;

            // Real, explicit user request: the notification log should reflect this
            // slot's full history on the server, not just what happened to occur this
            // process/connection -- see NotificationLog.cs's own class doc. Clearing
            // here, right before Connected fires and LocationManager.cs/ItemManager.cs
            // each rebuild their half from the server's own state, guarantees every
            // connect (including a reconnect after toggling AP MODE) ends at a clean,
            // correct picture rather than a stale or duplicated one.
            NotificationLog.Clear();

            _log.Msg($"Connected to Archipelago as '{slotName}'.");

            // Real bug found by live testing: `Connected?.Invoke()` used to be a plain
            // multicast delegate call. LocationManager.cs and ItemManager.cs both
            // subscribe to this event (in that construction order, see Mod.cs's
            // OnInitializeMelon) -- and .NET's multicast delegate invocation is NOT
            // fault-isolated: if the FIRST subscriber's handler throws anything at all,
            // every subscriber after it in the list is simply never invoked, with
            // nothing forcing that exception to surface anywhere obvious. On a room
            // with pre-existing checked locations, LocationManager.OnConnected() kicks
            // off Session.Locations.ScoutLocationsAsync(...) for its history resync --
            // if anything in that call's synchronous prefix throws (not yet confirmed
            // exactly what, but plausible given it's called the instant IsConnected
            // flips true), ItemManager.OnConnected() -- subscribed second -- would never
            // run at all, meaning it never subscribes to Session.Items.ItemReceived,
            // meaning the server's item-history replay never reaches UnlockState.Unlock(),
            // leaving every level except the always-unlocked first one looking locked
            // despite a genuinely live, correctly-connected session (explains why
            // Session-live reads like IsSecretCompleted()'s "CRACKED!" badges stayed
            // correct throughout -- only the replay-dependent local UnlockState was
            // affected). A brand new room has zero already-checked locations, so
            // LocationManager.OnConnected() hits its early return before ever calling
            // ScoutLocationsAsync -- which is exactly why reconnecting to a fresh room
            // "fixed" it while reconnecting to an in-progress one didn't. Invoking each
            // subscriber individually, with its own try/catch, guarantees one
            // subscriber's failure can never silently skip another's -- the real,
            // general fix, not just a patch for this one call site. See
            // LocationManager.cs/ItemManager.cs's own OnConnected for the matching
            // defensive try/catch around each handler's body.
            if (Connected != null)
            {
                foreach (Delegate handler in Connected.GetInvocationList())
                {
                    try
                    {
                        ((Action)handler)();
                    }
                    catch (Exception ex)
                    {
                        _log.Error($"A Connected event handler threw and was skipped: {ex}");
                    }
                }
            }
        }

        /// <summary>
        /// Whether this room's slot data (ExcludedLevelOrders, above) marked the level at
        /// this Order as excluded from tracking -- see Options.py's ExcludeSlowLevels.
        /// Callers pass a LevelEntry's own Order field, the same identifier
        /// fill_slot_data() sent this list as.
        /// </summary>
        public bool IsLevelExcluded(int order) => ExcludedLevelOrders.Contains(order);

        // Real, explicit user request: needed so turning Archipelago mode off
        // (Mod.SetEnabled(false), see Patches/ArchipelagoModeTogglePatch.cs) can actually
        // drop the connection rather than just ignoring it locally while the socket stays
        // open in the background. Session.Socket.DisconnectAsync() is the real, confirmed
        // API (found by reflecting the referenced Archipelago.MultiClient.Net.dll --
        // IArchipelagoSocketHelper.DisconnectAsync(), no ilspycmd available in this
        // environment at the time, reflection was the faster way to confirm it exists).
        // Deliberately fire-and-forget: awaiting it here would need this method to become
        // async, and the only thing it closes is the socket -- no game/Unity state to
        // wait on -- so blocking Unity's main thread for it isn't worth it, same reasoning
        // ItemManager already queues ItemReceived's off-thread events instead of handling
        // them inline.
        public void Disconnect()
        {
            if (Session == null)
            {
                IsConnected = false;
                return;
            }

            try
            {
                _ = Session.Socket.DisconnectAsync();
            }
            catch (Exception ex)
            {
                _log.Warning($"Error while disconnecting from the Archipelago server: {ex.Message}");
            }

            Session = null;
            IsConnected = false;
            _log.Msg("Disconnected from the Archipelago server.");
        }
    }
}
