using System;
using Archipelago.MultiClient.Net;
using Archipelago.MultiClient.Net.Enums;
using MelonLoader;

namespace SuperhotArchipelago.Core
{
    /// <summary>
    /// Thin wrapper around the official Archipelago.MultiClient.Net session. Owns the
    /// WebSocket connection to the AP server; ArchipelagoConnection itself never touches
    /// game/Unity state -- that's LocationManager/ItemManager's job.
    /// </summary>
    public class ArchipelagoConnection
    {
        private readonly MelonLogger.Instance _log;
        public ArchipelagoSession? Session { get; private set; }
        public bool IsConnected { get; private set; }

        // Real, explicit user request: Core/ArchipelagoConnectApp.cs surfaces connection
        // problems in-game instead of only in the (easy to miss) MelonLoader console.
        // Cleared at the start of every Connect() attempt, set on failure so the UI has
        // something more specific than "Not connected" to show.
        public string? LastError { get; private set; }

        // How many of the other 31 levels must be completed before "34 - Free" opens,
        // even once its own access item is received -- see Core/LevelAccessGuard.cs for
        // where this is actually enforced. Comes from this room's slot data (see below),
        // itself sourced from the player's own YAML (apworld/superhot/Options.py's
        // levels_required_for_free). The 25 here is just a fallback for before a
        // successful connect, or for a room generated by an apworld old enough not to
        // send this key at all -- kept equal to Options.py's own default so the two
        // can't quietly disagree if one is ever changed without the other.
        public int LevelsRequiredForFree { get; private set; } = 25;

        public event Action? Connected;

        public ArchipelagoConnection(MelonLogger.Instance log)
        {
            _log = log;
        }

        public void Connect(string server, string slotName, string? password = null)
        {
            LastError = null;
            IsConnected = false;

            if (string.IsNullOrEmpty(server) || string.IsNullOrEmpty(slotName))
            {
                LastError = "Server and Slot are both required.";
                _log.Warning($"Not connecting: {LastError}");
                return;
            }

            Session = ArchipelagoSessionFactory.CreateSession(server);

            // TODO: itemsHandlingFlags -- AllItems is the simplest starting point (get told
            // about every item including our own), can be narrowed later.
            //
            // The whole call is wrapped in a try/catch (needed once connecting became
            // reachable from in-game text entry, see Core/ArchipelagoConnectApp.cs):
            // TryConnectAndLogin can throw outright on some bad inputs (e.g. a malformed
            // server string) rather than just returning an unsuccessful result -- without
            // this, an in-game typo could throw past this method's caller and take down
            // more than just this one connect attempt.
            try
            {
                var result = Session.TryConnectAndLogin(
                    "SUPERHOT",
                    slotName,
                    ItemsHandlingFlags.AllItems,
                    password: password
                );

                if (!result.Successful)
                {
                    LastError = "Login failed -- check server address, slot name, and password.";
                    _log.Error($"Failed to connect to Archipelago server: {server}");
                    return;
                }

                // TryConnectAndLogin defaults requestSlotData to true (confirmed against
                // the client library's own source), so a successful LoginResult here is
                // always really a LoginSuccessful carrying this room's slot data -- the
                // "is" pattern match below is just the type-safe way to reach it, not a
                // real possibility of it being something else.
                if (result is LoginSuccessful success &&
                    success.SlotData.TryGetValue("levels_required_for_free", out object? rawRequired))
                {
                    // Comes back through Newtonsoft.Json as a boxed numeric type (long in
                    // practice for a plain JSON integer) -- Convert.ToInt32 handles that
                    // (or int/double, if the server ever serializes it differently)
                    // rather than assuming one specific boxed type and risking an
                    // InvalidCastException on a direct (int) cast.
                    LevelsRequiredForFree = Convert.ToInt32(rawRequired);
                    _log.Msg($"Slot data: {LevelsRequiredForFree} other levels required to enter '34 - Free'.");
                }
                else
                {
                    _log.Warning("Slot data had no 'levels_required_for_free' -- falling back to " +
                        $"{LevelsRequiredForFree}. Expected if this room was generated from an " +
                        "apworld version older than this feature.");
                }
            }
            catch (Exception ex)
            {
                LastError = ex.Message;
                _log.Error($"Failed to connect to Archipelago server '{server}': {ex.Message}");
                return;
            }

            IsConnected = true;
            _log.Msg($"Connected to Archipelago as '{slotName}'.");
            Connected?.Invoke();
        }
    }
}
